version: '3'
services:
    php-node:
        container_name: php-node
        build:
            context: ./
            dockerfile: php-node/Dockerfile
        volumes:
            - ./:/var/www
        restart: unless-stopped
